### ISSUE TITLE
logout() function throws error when `--update_time` is used

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/asExportIncremental#23]
```
Traceback (most recent call last):
  File "/home/harnold/asExportIncremental.py", line 391, in <module>
    logout()
  File "/home/harnold/asExportIncremental.py", line 88, in logout
    requests.post('{baseURL}/logout'.format(**dictionary), headers=headers)
NameError: global name 'headers' is not defined

```

Suspect the user is never logging into AS; hence they don't need to log out.

**Comment by pobocks** [comment]
It's definitely a missing "headers = authenticate()" in the update_time branch.
